//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_S2016_Lesson5C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hockey
    {
        public int hockeyID { get; set; }
        public string teamName1 { get; set; }
        public string teamName2 { get; set; }
        public int score1 { get; set; }
        public int score2 { get; set; }
        public int asists1 { get; set; }
        public int asists2 { get; set; }
    }
}
